package com.example.arman.e_route;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Bundle;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

public class Route extends AppCompatActivity {

    EditText frmtxt, totxt;
    TextView ruttxt;
    Button go;
    String ftxt,ttxt,bus,route;
    int flage = 1,i,found;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_route);

        frmtxt = (EditText) findViewById(R.id.from);
        Typeface frm_txt = Typeface.createFromAsset(getAssets(),
                "Mf Texas Spring.ttf");
        frmtxt.setTypeface(frm_txt);
        frmtxt.setTextColor(Color.parseColor("#00B8FF"));

        totxt = (EditText) findViewById(R.id.totxt);
        Typeface to_txt = Typeface.createFromAsset(getAssets(),
                "Mf Texas Spring.ttf");
        frmtxt.setTypeface(to_txt);
        frmtxt.setTextColor(Color.parseColor("#00B8FF"));

        ruttxt = (TextView) findViewById(R.id.routes);
        Typeface rut_txt = Typeface.createFromAsset(getAssets(),
                "Mf Texas Spring.ttf");
        ruttxt.setTypeface(rut_txt);

        go = (Button) findViewById(R.id.goButton);
        Typeface go_button = Typeface.createFromAsset(getAssets(),
                "Mf Texas Spring.ttf");
        go.setTypeface(go_button);

        go.setOnClickListener(new OnClickListener() {

            @Override
            public void onClick(View v) {
                ShowData();
            }
        });


    }

    public void CallData(){
        flage = 0;
        SQLiteDatabase db = openOrCreateDatabase("Road", MODE_PRIVATE, null);

        db.execSQL("DROP TABLE IF EXISTS BUSROUTE");


        db.execSQL("CREATE TABLE IF NOT EXISTS BUSROUTE (FROMGO VARCHAR,TOGO VARCHAR,BUS VARCHAR,ROUTE VARCHAR);");



        db.execSQL("INSERT INTO BUSROUTE VALUES ('UTTARA, MOHAKHALI, NABISCO','UTTARA, MOHAKHALI, NABISCO','BOLAKA, GAJIPUR PORIBAHAN, PROVATI BONOSRI','ABDULLAHPUR, UTTARA, MOHAKHALI, NABISCO')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('MIRPUR ','NABISCO','VIP27, PROJAPOTI, PROVATI ','ABDULLAHPUR, UTTARA, MOHAKHALI, NABISCO')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('MIRPUR-1, MIRPUR-2, MIRPUR-10, KALSHI','MIRPUR-1, MIRPUR-2, MIRPUR-10, KALSHI','KONOK','MIRPUR-1, MIRPUR-2, MIRPUR-10, KALSHI')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('ABDULLAHPUR, FARMGATE, UTTARA, AIRPORT, AZIMPUR, KHILKHET, MOHAKHALI, BONANI, MOTIJHEEL','ABDULLAHPURUTTARA, AIRPORT, AZIMPUR, KHILKHET, MOHAKHALI, BONANI, FARMGATE, MOTIJHEEL','BRTC','ABDULLAHPUR, UTTARA, AIRPORT, AZIMPUR, KHILKHET, MOHAKHALI, BONANI, FARMGATE, MOTIJHEEL')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('NEW MARKET, FARMGATE, GAZIPUR CHOURASTA, AZIMPUR, UTTARA, AIRPORT, KHILKHET, MOHAKHALI, BONANI,','NEW MARKET, UTTARA, AIRPORT, KHILKHET, MOHAKHALI, BONANI, FARMGATE, GAZIPUR CHOURASTA, AZIMPUR','VIP','NEW-MARKET, UTTARA, AIRPORT, KHILKHET, MOHAKHALI, BONANI, FARMGATE, GAZIPUR CHOURASTA, AZIMPUR')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('MIRPUR, ANSARCAMP, UTTARA, AIRPORT, BONANI, KHILKHET, ABDULLAHPUR','MIRPUR, AIRPORT, BONANI, KHILKHET, ANSARCAMP, UTTARA, ABDULLAHPUR','PROJAPOTI PORIBAHON','MIRPUR, UTTARA, AIRPORT, BONANI, KHILKHET, ANSARCAMP, ABDULLAHPUR')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('JATRABARI, MALIBAG, NABISCO, MOHAKHALI, RAMPURA, UTTARA, AIRPORT, BONANI, KHILKHET, NOTUNBAZAR','JATRABARI, MALIBAG, NABISCO, MOHAKHALI, RAMPURA, NOTUNBAZAR, UTTARA, AIRPORT, BONANI, KHILKHET','JATRABARI PORIBAHAN','JATRABARI, MALIBAG, NABISCO, MOHAKHALI, RAMPURA, NOTUNBAZAR, UTTARA, AIRPORT, BONANI, KHILKHET')");

        db.execSQL("INSERT INTO BUSROUTE VALUES ('GULISTAN, POLTON, MOGBAZAR, MOHAKHALI','GULISTAN, POLTON, MOGBAZAR, MOHAKHALI','PROVATI BANASHREE','GULISTAN, POLTON, MOGBAZAR, MOHAKHALI')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('MOHAKHALI, AIRPORT, UTTARA, ABDULLAHPUR','MOHAKHALI, AIRPORT, UTTARA, ABDULLAHPUR','ASHULIA CLASSIC','MOHAKHALI, AIRPORT, UTTARA, ABDULLAHPUR')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('GABTOLI, ABDULLAHPUR, MIRPUR, GAZIPUR CHOURASTA, KALSHI','GABTOLI, ABDULLAHPUR, MIRPUR, GAZIPUR CHOURASTA, KALSHI','BOSUMOTI','GABTOLI, ABDULLAHPUR, MIRPUR, GAZIPUR CHOURASTA, KALSHI')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('MIRPUR, ANSARCAMP, UTTARA, ABDULLAHPUR, KALSHI','MIRPUR, ANSARCAMP, UTTARA, ABDULLAHPUR, KALSHI','NEW PALLABI EXPRESS','MIRPUR, ANSARCAMP, UTTARA, ABDULLAHPUR, KALSHI')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('SAVAR, GABTOLI, SHYAMOLI, AGARGAO, KAKOLI','SAVAR, GABTOLI, SHYAMOLI, AGARGAO, KAKOLI','RUPKATHA','SAVAR, GABTOLI, SHYAMOLI, AGARGAO, KAKOLI')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('GULISTAN, MOGBAZAR, MOHAKHALI, TONGI, GAZIPUR','GULISTAN, MOGBAZAR, MOHAKHALI, TONGI, GAZIPUR','GAZIPUR PARIBAHAN','GULISTAN, MOGBAZAR, MOHAKHALI, TONGI, GAZIPUR')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('TONGI, AIRPORT, RAMPURA, MALIBAG, JATRABARI','TONGI, AIRPORT, RAMPURA, MALIBAG, JATRABARI','JM SITTING','TONGI, AIRPORT, RAMPURA, MALIBAG, JATRABARI')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('JATRABARI, KHILGAO, MALIBAG, RAMPURA, SAIDABAD, BISSOROAD, AIRPORT, TONGI, NOTUNBAZAR, BADDA','JATRABARI, KHILGAO, MALIBAG, RAMPURA, SAIDABAD, BISSOROAD, AIRPORT, TONGI, NOTUNBAZAR, BADDA','GREAT TURAG','JATRABARI, KHILGAO, MALIBAG, RAMPURA, SAIDABAD, BISSOROAD, AIRPORT, TONGI, NOTUNBAZAR, BADDA')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('SADARGHAT, GULISTAN, BISSOROAD, AIRPORT, KURIL, RAMPURA, GAZIPUR, TONGI','SADARGHAT, GULISTAN, BISSOROAD, AIRPORT,KURIL,RAMPURA,GAZIPUR,TONGI','SUPROVAT','SADARGHAT, GULISTAN, BISSOROAD, AIRPORT, KURIL, RAMPURA, GAZIPUR, TONGI')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('AIRPORT, UTTARA, ABDULLAHPUR, GULISTAN, SHAHBAG, FARMGATE','AIRPORT, UTTARA, ABDULLAHPUR, GULISTAN, SHAHBAG, FARMGATE','AIRPORT BONGONODHU AVENUE','AIRPORT, UTTARA, ABDULLAHPUR, GULISTAN, SHAHBAG, FARMGATE')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('SAYEDABAD, UTTARA, MALIBAG, RAMPURA, BADDA, AIRPORT, TONGI','SAYEDABAD, UTTARA, MALIBAG, RAMPURA, BADDA, AIRPORT, TONGI','ANABIL SUPER','SAYEDABAD, MALIBAG, RAMPURA, BADDA, AIRPORT, TONGI')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('GABTOLI, MIRPUR-1, MIRPUR-10, KALSHI, JAMUNA FUTURE PARK, NATUN BAZAR, BADDA','GABTOLI, MIRPUR-1, MIRPUR-10, KALSHI, JAMUNA FUTURE PARK, NATUN BAZAR, BADDA','AKIK PORIBOHON','GABTOLI, MIRPUR-1, MIRPUR-10, KALSHI, JAMUNA FUTURE PARK, NATUN BAZAR, BADDA')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('MIRPUR-10, CANTONMENT, BANANI, NOTUN BAZAR','MIRPUR-10, CANTONMENT, BANANI, NOTUN BAZAR','TRUST LINE','MIRPUR-10, CANTONMENT, BANANI, NOTUN BAZAR')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('SHIYA MASJID, SHYAMOLI, AGARGOAN, MIRPUR-10, KALSHI, BISSHOROAD, AIRPORT, UTTARA, ABDULLAHPUR','SHIYA MASJID, SHYAMOLI, AGARGOAN, MIRPUR-10, KALSHI, BISSHOROAD, AIRPORT, UTTARA, ABDULLAHPUR','TETULIA PORIBOHON','SHIYA MASJID, SHYAMOLI, AGARGOAN, MIRPUR-10, KALSHI, BISSHOROAD, AIRPORT, UTTARA, ABDULLAHPUR')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('AGARGOAN, MIRPUR-10, KALSHI, BISSHOROAD, AIRPORT, UTTARA, ABDULLAHPUR','AGARGOAN, MIRPUR-10, KALSHI, BISSHOROAD, AIRPORT, UTTARA, ABDULLAHPUR','JABALE NOOR PORIBOHON, OVIJAT PORIBOHON','AGARGOAN, MIRPUR-10, KALSHI, BISSHOROAD, AIRPORT, UTTARA, ABDULLAHPUR')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('MIRPUR SONY CINEMA HALL, MIRPUR-10, KAZIPARA, SHEWRAPARA, MOHAKHALI, GULSHAN-1, BADDA, RAMPURA, BONOSHRI','MIRPUR SONY CINEMA HALL, MIRPUR-10, KAZIPARA, SHEWRAPARA, MOHAKHALI, GULSHAN-1, BADDA, RAMPURA, BONOSHRI','ALIF PORIBOHON, ROIS PORIBOHON','MIRPUR SONY CINEMA HALL, MIRPUR-10, KAZIPARA, SHEWRAPARA, MOHAKHALI, GULSHAN-1, BADDA, RAMPURA, BONOSHRI')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('MIRPUR SONY CINEMA HALL, MIRPUR-10, KAZIPARA, SHEWRAPARA, MOHAKHALI, GULSHAN-1, BADDA, RAMPURA, KHILGOAN KHIDMA HOSPITAL','MIRPUR SONY CINEMA HALL, MIRPUR-10, KAZIPARA, SHEWRAPARA, MOHAKHALI, GULSHAN-1, BADDA, RAMPURA, KHILGOAN KHIDMA HOSPITAL','HIMACHOL PORIBOHON','MIRPUR SONY CINEMA HALL, MIRPUR-10, KAZIPARA, SHEWRAPARA, MOHAKHALI, GULSHAN-1, BADDA, RAMPURA, KHILGOAN KHIDMA HOSPITAL')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('GABTOLI, MIRPUR-1, MIRPUR-10, KALSHI, BISSHOROAD, AIRPORT, UTTARA, ABDULLAHPUR','GABTOLI, MIRPUR-1, MIRPUR-10, KALSHI, BISSHOROAD, AIRPORT, UTTARA, ABDULLAHPUR','PROJAPOTI PORIBOHON, NEW PALLABI EXPRESS, KONOK PORIBOHON','GABTOLI, MIRPUR-1, MIRPUR-10, KALSHI, BISSHOROAD, AIRPORT, UTTARA, ABDULLAHPUR')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('ROOPNAGAR ABASHIK, MIRPUR-2, MIRPUR-1, KHAMARBARI, FARMGATE, GULISTAN, KERANIGANJ','ROOPNAGAR ABASHIK, MIRPUR-2, MIRPUR-1, KHAMARBARI, FARMGATE, GULISTAN, KERANIGANJ','EVEREST PORIBOHON','ROOPNAGAR ABASHIK, MIRPUR-2, MIRPUR-1, KHAMARBARI, FARMGATE, GULISTAN, KERANIGANJ')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('ROOPNAGAR ABASHIK, MIRPUR-2, MIRPUR-1, KOLYANPUR, SHYAMOLI, ASADGATE, SHUKRABAD, KOLABAGAN, SCIENCE LAB, NEW MARKET, NILKHET, AZIMPUR','ROOPNAGAR ABASHIK, MIRPUR-2, MIRPUR-1, KOLYANPUR, SHYAMOLI, ASADGATE, SHUKRABAD, KOLABAGAN, SCIENCE LAB, NEW MARKET, NILKHET, AZIMPUR','ASHIRBAD PORIBOHON, BIHONGO PORIBOHON','ROOPNAGAR ABASHIK, MIRPUR-2, MIRPUR-1, KOLYANPUR, SHYAMOLI, ASADGATE, SHUKRABAD, KOLABAGAN, SCIENCE LAB, NEW MARKET, NILKHET, AZIMPUR')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('NATIONAL ZOO, MIRPUR 1, GULISTAN, KERANIGANJ, BABUBAJAR BRIDGE','NATIONAL ZOO, MIRPUR 1, GULISTAN, KERANIGANJ, BABUBAJAR BRIDGE','DISHARI PORIBOHON','NATIONAL ZOO, MIRPUR 1, GULISTAN, KERANIGANJ, BABUBAJAR BRIDGE')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('MIRPUR-10, MIRPUR-1, TECHNICAL, KOLYANPUR, ASADGATE, KOLABAGAN, SCIENCE LAB, NEW MARKET, NILKHET, AZIMPUR, TSC, SHAHBAG, PRESS CLUB, GULISTAN, TIKATULI, JATRABARI','MIRPUR-10, MIRPUR-1, TECHNICAL, KOLYANPUR, ASADGATE, KOLABAGAN, SCIENCE LAB, NEW MARKET, NILKHET, AZIMPUR, TSC, SHAHBAG, PRESS CLUB, GULISTAN, TIKATULI, JATRABARI','BIKOLPO SERVICE 1/E','MIRPUR-10, MIRPUR-1, TECHNICAL, KOLYANPUR, ASADGATE, KOLABAGAN, SCIENCE LAB, NEW MARKET, NILKHET, AZIMPUR, TSC, SHAHBAG, PRESS CLUB, GULISTAN, TIKATULI, JATRABARI')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('MIRPUR-12, MIRPUR-10, AGARGOAN, FARMGATE, SHAHBAG, GULISTAN, MOTIJHIL','MIRPUR-12, MIRPUR-10, AGARGOAN, FARMGATE, SHAHBAG, GULISTAN, MOTIJHIL','BIKOLPO AUTO SERVICE, HAZI PORIBOHON','MIRPUR-12, MIRPUR-10, AGARGOAN, FARMGATE, SHAHBAG, GULISTAN, MOTIJHIL')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('NATIONAL ZOO, MIRPUR-1, AGARGOAN, BIJOY SARANI, FARMGATE, BANGLA MOTOR, MOGBAZAR, MALIBAG, KOMLAPUR','NATIONAL ZOO, MIRPUR-1, AGARGOAN, BIJOY SARANI, FARMGATE, BANGLA MOTOR, MOGBAZAR, MALIBAG, KOMLAPUR','SOKOLPO PORIBOHON','NATIONAL ZOO, MIRPUR-1, AGARGOAN, BIJOY SARANI, FARMGATE, BANGLA MOTOR, MOGBAZAR, MALIBAG, KOMLAPUR')");
        db.execSQL("INSERT INTO BUSROUTE VALUES ('NIKUNJU, MALIBAG, BANANI, MOHAKHALI, NABISCO, SAAT RASTA','NIKUNJU, MALIBAG, BANANI, MOHAKHALI, NABISCO, SAAT RASTA','BOLAKA, PROVATI, GAZIPUR PORIBOHON','NIKUNJU, MALIBAG, BANANI, MOHAKHALI, NABISCO, SAAT RASTA')");
        db.close();
    }

    public void ShowData(){
        try{

            found = 0;
            if(flage == 1)
                CallData();

            ruttxt.setText("");

            ftxt = frmtxt.getText()+"";

            ttxt = totxt.getText()+"";
            Log.d("Database operations", "Table created");

            if(ftxt.length()!=0 && ttxt.length()!=0){

                ftxt = "%"+ftxt+"%";  //making for like operator
                ttxt = "%"+ttxt+"%";


                ruttxt.setText("");

                SQLiteDatabase db2 = openOrCreateDatabase("Road", MODE_PRIVATE, null);


                final Cursor cursor = db2.rawQuery("SELECT * FROM BUSROUTE WHERE FROMGO LIKE '"+ftxt+"' AND TOGO LIKE '"+ttxt+"'", null);

                if(cursor.moveToFirst())
                {
                    found = 1;
                    i=1;
                    do{

                        bus = cursor.getString(cursor.getColumnIndex("BUS"));
                        route = cursor.getString(cursor.getColumnIndex("ROUTE"));
                        ruttxt.append("Bus "+i+": "+bus+"\n"+"Route: "+route+"\n\n");


                        ruttxt.setTextColor(Color.parseColor("#ECF0F1"));
                        i++;

                    }while(cursor.moveToNext()!=false);
                }
                db2.close();

                if(found == 0){
                    Toast.makeText(getApplicationContext(), "Route not found", Toast.LENGTH_SHORT).show();

                }
            }
            else{
                Toast.makeText(getApplicationContext(), "Please Enter Your Destination", Toast.LENGTH_SHORT).show();
            }

        }catch(Exception e){
            Toast.makeText(getApplicationContext(), "I am crashed", Toast.LENGTH_SHORT).show();

        }
    }

    }

